name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.26.4
    strategy:
      matrix:
        sample: [blink]
        target: [esp32s2_saola]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: learn

      - name: Set variables
        working-directory: learn
        id: vars
        run: |
             echo "::set-output name=branch::${GITHUB_REF#refs/*/}"
             echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Initialize
        working-directory: learn
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build ${{ matrix.sample }} for ${{ matrix.target }}
        working-directory: learn
        run: |
          west build -b ${{ matrix.target }} -s samples/${{ matrix.sample }} -p
          mkdir -p .out
          cp build/zephyr/app_update.bin .out/${{ matrix.sample }}_${{ matrix.target }}_app_update.bin
          cp build/zephyr/merged.hex .out/${{ matrix.sample }}_${{ matrix.target }}_merged.hex

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: learn_${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
          path: learn/.out/
